# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TE_interface.ui',
# licensing of 'TE_interface.ui' applies.
#
# Created: Fri Sep  6 12:49:51 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(269, 301)
        self.Run = QtWidgets.QPushButton(Form)
        self.Run.setGeometry(QtCore.QRect(10, 10, 120, 23))
        self.Run.setObjectName("Run")
        self.Freeze = QtWidgets.QPushButton(Form)
        self.Freeze.setGeometry(QtCore.QRect(140, 10, 120, 23))
        self.Freeze.setObjectName("Freeze")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 90, 251, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(5, 5, 130, 16))
        self.label.setObjectName("label")
        self.Go_mal = QtWidgets.QPushButton(self.frame)
        self.Go_mal.setGeometry(QtCore.QRect(10, 140, 231, 23))
        self.Go_mal.setObjectName("Go_mal")
        self.Mal_list = QtWidgets.QListWidget(self.frame)
        self.Mal_list.setGeometry(QtCore.QRect(10, 80, 231, 51))
        self.Mal_list.setObjectName("Mal_list")
        self.Mal_nub = QtWidgets.QLineEdit(self.frame)
        self.Mal_nub.setGeometry(QtCore.QRect(70, 30, 50, 20))
        self.Mal_nub.setObjectName("Mal_nub")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 60, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 60, 20))
        self.label_3.setObjectName("label_3")
        self.Mal_type = QtWidgets.QLineEdit(self.frame)
        self.Mal_type.setGeometry(QtCore.QRect(190, 30, 50, 20))
        self.Mal_type.setObjectName("Mal_type")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 60, 20))
        self.label_4.setObjectName("label_4")
        self.Mal_time = QtWidgets.QLineEdit(self.frame)
        self.Mal_time.setGeometry(QtCore.QRect(70, 50, 50, 20))
        self.Mal_time.setObjectName("Mal_time")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 251, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Initial = QtWidgets.QPushButton(self.frame_2)
        self.Initial.setGeometry(QtCore.QRect(10, 10, 75, 22))
        self.Initial.setObjectName("Initial")
        self.Initial_list = QtWidgets.QComboBox(self.frame_2)
        self.Initial_list.setGeometry(QtCore.QRect(90, 10, 151, 22))
        self.Initial_list.setObjectName("Initial_list")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Initial_list.addItem("")
        self.Go_db = QtWidgets.QPushButton(Form)
        self.Go_db.setGeometry(QtCore.QRect(20, 270, 231, 23))
        self.Go_db.setObjectName("Go_db")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.Run.setText(QtWidgets.QApplication.translate("Form", "Run", None, -1))
        self.Freeze.setText(QtWidgets.QApplication.translate("Form", "Freeze", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Malfunction", None, -1))
        self.Go_mal.setText(QtWidgets.QApplication.translate("Form", "Go Malfunction", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Mal_nub", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Mal_type", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Mal_time", None, -1))
        self.Initial.setText(QtWidgets.QApplication.translate("Form", "Initial", None, -1))
        self.Initial_list.setItemText(0, QtWidgets.QApplication.translate("Form", "1. 100%", None, -1))
        self.Initial_list.setItemText(1, QtWidgets.QApplication.translate("Form", "2. 80%", None, -1))
        self.Initial_list.setItemText(2, QtWidgets.QApplication.translate("Form", "3. 70%", None, -1))
        self.Initial_list.setItemText(3, QtWidgets.QApplication.translate("Form", "4. 60% (??)", None, -1))
        self.Initial_list.setItemText(4, QtWidgets.QApplication.translate("Form", "5. 13% (??)", None, -1))
        self.Initial_list.setItemText(5, QtWidgets.QApplication.translate("Form", "6. 7% (??)", None, -1))
        self.Initial_list.setItemText(6, QtWidgets.QApplication.translate("Form", "7. 2% (??)", None, -1))
        self.Initial_list.setItemText(7, QtWidgets.QApplication.translate("Form", "8. Reactor Critical", None, -1))
        self.Initial_list.setItemText(8, QtWidgets.QApplication.translate("Form", "9. Hotstandby", None, -1))
        self.Initial_list.setItemText(9, QtWidgets.QApplication.translate("Form", "10. Hotshutdown", None, -1))
        self.Initial_list.setItemText(10, QtWidgets.QApplication.translate("Form", "11. Cold shutdown", None, -1))
        self.Initial_list.setItemText(11, QtWidgets.QApplication.translate("Form", "12. Hot standby", None, -1))
        self.Initial_list.setItemText(12, QtWidgets.QApplication.translate("Form", "13. Cold shutdown 1", None, -1))
        self.Initial_list.setItemText(13, QtWidgets.QApplication.translate("Form", "14. Hot showdown(colddown)", None, -1))
        self.Initial_list.setItemText(14, QtWidgets.QApplication.translate("Form", "15. Hot shut to Hot standby", None, -1))
        self.Initial_list.setItemText(15, QtWidgets.QApplication.translate("Form", "16. Test 70%", None, -1))
        self.Initial_list.setItemText(16, QtWidgets.QApplication.translate("Form", "17. 2%(real)", None, -1))
        self.Go_db.setText(QtWidgets.QApplication.translate("Form", "Save_DB", None, -1))

