# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trend_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(721, 548)
        self.Test_label = QtWidgets.QLabel(Dialog)
        self.Test_label.setGeometry(QtCore.QRect(10, 10, 56, 12))
        self.Test_label.setObjectName("Test_label")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 256, 31))
        self.listWidget.setObjectName("listWidget")
        self.Rod_1 = QtWidgets.QLabel(Dialog)
        self.Rod_1.setGeometry(QtCore.QRect(30, 100, 41, 141))
        self.Rod_1.setStyleSheet("background-color: rgb(0, 22, 147);")
        self.Rod_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_1.setText("")
        self.Rod_1.setObjectName("Rod_1")
        self.Rod_1_back = QtWidgets.QLabel(Dialog)
        self.Rod_1_back.setGeometry(QtCore.QRect(30, 100, 41, 228))
        self.Rod_1_back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Rod_1_back.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_1_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Rod_1_back.setLineWidth(1)
        self.Rod_1_back.setText("")
        self.Rod_1_back.setObjectName("Rod_1_back")
        self.Rod_2 = QtWidgets.QLabel(Dialog)
        self.Rod_2.setGeometry(QtCore.QRect(90, 100, 41, 141))
        self.Rod_2.setStyleSheet("background-color: rgb(0, 22, 147);")
        self.Rod_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_2.setText("")
        self.Rod_2.setObjectName("Rod_2")
        self.Rod_2_back = QtWidgets.QLabel(Dialog)
        self.Rod_2_back.setGeometry(QtCore.QRect(90, 100, 41, 228))
        self.Rod_2_back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Rod_2_back.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_2_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Rod_2_back.setLineWidth(1)
        self.Rod_2_back.setText("")
        self.Rod_2_back.setObjectName("Rod_2_back")
        self.Rod_3_back = QtWidgets.QLabel(Dialog)
        self.Rod_3_back.setGeometry(QtCore.QRect(150, 100, 41, 228))
        self.Rod_3_back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Rod_3_back.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_3_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Rod_3_back.setLineWidth(1)
        self.Rod_3_back.setText("")
        self.Rod_3_back.setObjectName("Rod_3_back")
        self.Rod_4_back = QtWidgets.QLabel(Dialog)
        self.Rod_4_back.setGeometry(QtCore.QRect(210, 100, 41, 228))
        self.Rod_4_back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Rod_4_back.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_4_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Rod_4_back.setLineWidth(1)
        self.Rod_4_back.setText("")
        self.Rod_4_back.setObjectName("Rod_4_back")
        self.Rod_3 = QtWidgets.QLabel(Dialog)
        self.Rod_3.setGeometry(QtCore.QRect(150, 100, 41, 141))
        self.Rod_3.setStyleSheet("background-color: rgb(0, 22, 147);")
        self.Rod_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_3.setText("")
        self.Rod_3.setObjectName("Rod_3")
        self.Rod_4 = QtWidgets.QLabel(Dialog)
        self.Rod_4.setGeometry(QtCore.QRect(210, 100, 41, 141))
        self.Rod_4.setStyleSheet("background-color: rgb(0, 22, 147);")
        self.Rod_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Rod_4.setText("")
        self.Rod_4.setObjectName("Rod_4")
        self.Dis_Rod_1 = QtWidgets.QLabel(Dialog)
        self.Dis_Rod_1.setGeometry(QtCore.QRect(30, 70, 41, 20))
        self.Dis_Rod_1.setStyleSheet("font: 9pt \"HY헤드라인M\";\n"
"background-color: rgb(255, 255, 255);")
        self.Dis_Rod_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Dis_Rod_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Dis_Rod_1.setObjectName("Dis_Rod_1")
        self.Dis_Rod_2 = QtWidgets.QLabel(Dialog)
        self.Dis_Rod_2.setGeometry(QtCore.QRect(90, 70, 41, 20))
        self.Dis_Rod_2.setStyleSheet("font: 9pt \"HY헤드라인M\";\n"
"background-color: rgb(255, 255, 255);")
        self.Dis_Rod_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Dis_Rod_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Dis_Rod_2.setObjectName("Dis_Rod_2")
        self.Dis_Rod_3 = QtWidgets.QLabel(Dialog)
        self.Dis_Rod_3.setGeometry(QtCore.QRect(150, 70, 41, 20))
        self.Dis_Rod_3.setStyleSheet("font: 9pt \"HY헤드라인M\";\n"
"background-color: rgb(255, 255, 255);")
        self.Dis_Rod_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Dis_Rod_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Dis_Rod_3.setObjectName("Dis_Rod_3")
        self.Dis_Rod_4 = QtWidgets.QLabel(Dialog)
        self.Dis_Rod_4.setGeometry(QtCore.QRect(210, 70, 41, 20))
        self.Dis_Rod_4.setStyleSheet("font: 9pt \"HY헤드라인M\";\n"
"background-color: rgb(255, 255, 255);")
        self.Dis_Rod_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Dis_Rod_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Dis_Rod_4.setObjectName("Dis_Rod_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 100, 421, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Rod_his = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Rod_his.setContentsMargins(0, 0, 0, 0)
        self.Rod_his.setObjectName("Rod_his")
        self.Rod_2_back.raise_()
        self.Rod_1_back.raise_()
        self.Rod_4_back.raise_()
        self.Rod_3_back.raise_()
        self.Test_label.raise_()
        self.listWidget.raise_()
        self.Rod_1.raise_()
        self.Rod_2.raise_()
        self.Rod_3.raise_()
        self.Rod_4.raise_()
        self.Dis_Rod_1.raise_()
        self.Dis_Rod_2.raise_()
        self.Dis_Rod_3.raise_()
        self.Dis_Rod_4.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Test_label.setText(_translate("Dialog", "Value"))
        self.Dis_Rod_1.setText(_translate("Dialog", "100"))
        self.Dis_Rod_2.setText(_translate("Dialog", "100"))
        self.Dis_Rod_3.setText(_translate("Dialog", "100"))
        self.Dis_Rod_4.setText(_translate("Dialog", "100"))

